import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { toast } from 'sonner';
import clsx from 'clsx';
import AppShell from '../../components/layout/AppShell';
import { HospitalAPI, PatientBill, PatientPayment } from '../../api/endpoints';
import { useAuth } from '../../store/auth';
import { useHospital } from '../../hooks/useHospital';
import Spinner from '../../components/feedback/Spinner';

const Invoice = () => {
  const { patientId, invoiceNumber } = useParams<{ patientId: string; invoiceNumber: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();
  const hospitalId = user?.hospital_id || '1';
  const { hospitalName } = useHospital();

  // Fetch patient billing data
  const { data: billingData, isLoading } = useQuery({
    queryKey: ['hospital', 'patient', 'billing', hospitalId, patientId],
    queryFn: async () => {
      if (!patientId) throw new Error('Patient ID is required');
      return await HospitalAPI.getPatientBilling(hospitalId, patientId);
    },
    enabled: !!patientId,
  });

  // Find the invoice
  const outstandingBill = billingData?.outstandingBills?.find(b => b.invoice_number === invoiceNumber);
  const paymentRecord = billingData?.paymentHistory?.find(p => p.invoice_number === invoiceNumber);
  const invoice = outstandingBill || paymentRecord;
  const isOutstandingBill = !!outstandingBill;

  // Fetch patient data for invoice header
  const { data: patient } = useQuery({
    queryKey: ['hospital', 'patient', hospitalId, patientId],
    queryFn: async () => {
      if (!patientId) throw new Error('Patient ID is required');
      return await HospitalAPI.getPatient(hospitalId, patientId);
    },
    enabled: !!patientId,
  });

  const handleDownloadInvoice = () => {
    if (!invoice || !patient) return;

    const invoiceContent = `
============================================================
                    INVOICE
============================================================

${hospitalName}
Invoice Number: ${invoice.invoice_number}
Date: ${isOutstandingBill ? new Date((invoice as PatientBill).due_date).toLocaleDateString() : new Date((invoice as PatientPayment).date).toLocaleDateString()}
Status: ${invoice.status || 'N/A'}

------------------------------------------------------------
BILL TO:
------------------------------------------------------------
${patient.first_name} ${patient.last_name}
${patient.email || ''}
${patient.phone || ''}
MRN: ${patient.mrn}

------------------------------------------------------------
INVOICE DETAILS:
------------------------------------------------------------
Service: ${invoice.service || 'Medical Services'}
Amount: $${invoice.amount.toFixed(2)}
${isOutstandingBill ? `Due Date: ${new Date((invoice as PatientBill).due_date).toLocaleDateString()}` : `Payment Date: ${new Date((invoice as PatientPayment).date).toLocaleDateString()}`}

------------------------------------------------------------
TOTAL AMOUNT: $${invoice.amount.toFixed(2)}
============================================================

Generated by ${hospitalName} via HMSA System
${new Date().toLocaleString()}
    `.trim();

    const blob = new Blob([invoiceContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `invoice-${invoice.invoice_number}-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    window.URL.revokeObjectURL(url);
    document.body.removeChild(a);
    toast.success('Invoice downloaded successfully');
  };

  if (isLoading) {
    return (
      <AppShell>
        <div className="flex items-center justify-center min-h-[400px]">
          <Spinner size="lg" />
        </div>
      </AppShell>
    );
  }

  if (!invoice) {
    return (
      <AppShell>
        <div className="max-w-7xl mx-auto">
          <div className="bg-red-50 dark:bg-red-900/30 border border-red-200 dark:border-red-800 rounded-lg p-4">
            <p className="text-red-700 dark:text-red-300">
              Invoice not found.
            </p>
            <button
              onClick={() => navigate(`/hospital/patients/${patientId}`)}
              className="mt-4 px-4 py-2 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors"
            >
              Back to Patient Profile
            </button>
          </div>
        </div>
      </AppShell>
    );
  }

  const isPaid = invoice.status === 'paid' || (isOutstandingBill && (invoice as PatientBill).status === 'paid');
  const isOverdue = isOutstandingBill && 
                    new Date((invoice as PatientBill).due_date) < new Date() && 
                    (invoice as PatientBill).status !== 'paid';

  return (
    <AppShell>
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-6 flex flex-wrap items-center gap-3">
          <button
            onClick={() => navigate(`/hospital/patients/${patientId}`)}
            className="flex items-center gap-2 text-subtle-light dark:text-subtle-dark hover:text-foreground-light dark:hover:text-foreground-dark transition-colors whitespace-nowrap"
          >
            <span className="material-symbols-outlined text-sm">arrow_back</span>
            <span className="text-sm">Back to Patient</span>
          </button>
          <span className="text-subtle-light dark:text-subtle-dark hidden sm:inline">|</span>
          <h1 className="text-xl sm:text-2xl md:text-3xl font-bold text-foreground-light dark:text-foreground-dark">
            Invoice {invoice.invoice_number}
          </h1>
        </div>

        {/* Invoice Card */}
        <div className="bg-card-light dark:bg-card-dark rounded-xl shadow-soft p-6 sm:p-8">
          {/* Invoice Header */}
          <div className="border-b border-border-light dark:border-border-dark pb-6 mb-6">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
              <div>
                <h2 className="text-xl font-semibold text-foreground-light dark:text-foreground-dark mb-1">
                  {hospitalName}
                </h2>
                <h2 className="text-2xl font-bold text-foreground-light dark:text-foreground-dark mb-2">
                  INVOICE
                </h2>
                <p className="text-subtle-light dark:text-subtle-dark">
                  Invoice Number: <span className="font-semibold text-foreground-light dark:text-foreground-dark">{invoice.invoice_number}</span>
                </p>
              </div>
              <div className="text-right">
                <span className={clsx(
                  "inline-flex items-center px-3 py-1 rounded-full text-sm font-medium",
                  isPaid
                    ? "bg-green-100 dark:bg-green-900/20 text-green-700 dark:text-green-300"
                    : isOverdue
                    ? "bg-red-100 dark:bg-red-900/20 text-red-700 dark:text-red-300"
                    : "bg-yellow-100 dark:bg-yellow-900/20 text-yellow-700 dark:text-yellow-300"
                )}>
                  {isPaid ? 'Paid' : isOverdue ? 'Overdue' : 'Pending'}
                </span>
              </div>
            </div>
          </div>

          {/* Bill To Section */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-subtle-light dark:text-subtle-dark mb-3 uppercase">
              Bill To:
            </h3>
            <div className="bg-background-light dark:bg-background-dark/50 p-4 rounded-lg border border-border-light dark:border-border-dark">
              <p className="font-semibold text-foreground-light dark:text-foreground-dark">
                {patient?.first_name} {patient?.last_name}
              </p>
              {patient?.email && (
                <p className="text-sm text-subtle-light dark:text-subtle-dark mt-1">
                  {patient.email}
                </p>
              )}
              {patient?.phone && (
                <p className="text-sm text-subtle-light dark:text-subtle-dark">
                  {patient.phone}
                </p>
              )}
              {patient?.mrn && (
                <p className="text-sm text-subtle-light dark:text-subtle-dark mt-2">
                  MRN: {patient.mrn}
                </p>
              )}
            </div>
          </div>

          {/* Invoice Details */}
          <div className="mb-6">
            <h3 className="text-sm font-semibold text-subtle-light dark:text-subtle-dark mb-3 uppercase">
              Invoice Details:
            </h3>
            <div className="space-y-3">
              <div className="flex justify-between items-center py-2 border-b border-border-light dark:border-border-dark">
                <span className="text-subtle-light dark:text-subtle-dark">Service:</span>
                <span className="font-semibold text-foreground-light dark:text-foreground-dark">
                  {invoice.service || 'Medical Services'}
                </span>
              </div>
              {isOutstandingBill && (
                <div className="flex justify-between items-center py-2 border-b border-border-light dark:border-border-dark">
                  <span className="text-subtle-light dark:text-subtle-dark">Due Date:</span>
                  <span className="font-semibold text-foreground-light dark:text-foreground-dark">
                    {new Date((invoice as PatientBill).due_date).toLocaleDateString('en-US', { 
                      month: 'long', 
                      day: 'numeric', 
                      year: 'numeric' 
                    })}
                  </span>
                </div>
              )}
              {!isOutstandingBill && (
                <div className="flex justify-between items-center py-2 border-b border-border-light dark:border-border-dark">
                  <span className="text-subtle-light dark:text-subtle-dark">Payment Date:</span>
                  <span className="font-semibold text-foreground-light dark:text-foreground-dark">
                    {new Date((invoice as PatientPayment).date).toLocaleDateString('en-US', { 
                      month: 'long', 
                      day: 'numeric', 
                      year: 'numeric' 
                    })}
                  </span>
                </div>
              )}
              <div className="flex justify-between items-center py-2">
                <span className="text-lg font-semibold text-foreground-light dark:text-foreground-dark">Total Amount:</span>
                <span className="text-2xl font-bold text-primary">
                  ${invoice.amount.toFixed(2)}
                </span>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-wrap gap-3 pt-6 border-t border-border-light dark:border-border-dark">
            <button
              onClick={handleDownloadInvoice}
              className="flex-1 sm:flex-none h-11 px-6 rounded-lg font-semibold bg-background-light dark:bg-background-dark border border-border-light dark:border-border-dark text-foreground-light dark:text-foreground-dark hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors flex items-center justify-center gap-2"
            >
              <span className="material-symbols-outlined text-base">download</span>
              Download Invoice
            </button>
            <button
              onClick={() => navigate(`/hospital/patients/${patientId}`)}
              className="flex-1 sm:flex-none h-11 px-6 rounded-lg font-semibold bg-primary text-white shadow-soft hover:bg-primary/90 transition-colors"
            >
              Back to Patient
            </button>
          </div>
        </div>
      </div>
    </AppShell>
  );
};

export default Invoice;

